$NULL=Read-Host "This is starts 1.ps1";
#0.0;
#Common drive;
$zzProfileConfirmation = 'This profile loaded successfully!';
$scriptLocation = "M:\114320 Quality Assur\quality\Common folder\Scripts";
#zRate = 41.73;
$res = "Restricted";
$RS = "RemoteSigned";
#The goal is now to create a new item on the desktop, then remove it.;
# Here's a location;
$loc = "C:\users\p114320a\desktop\Narnia2.0";#I make so many references to this fictious location anyway...;
#1.0.0;#New-Item -ItemType "directory" -Path "C:\users\p114320a\desktop\alsifuh8";#This will be updated on the next line.;
#1.0.1;#New-Item -ItemType "directory" -Path "$loc";
#1.0.1;#Set-Location "C:\users\p114320a\desktop\alsifuh8";
New-Alias -Name SEP -Value Set-ExecutionPolicy -Description "This purpose of this alias is to shorten the command of Set-ExecutionPolicy to something a little more keyboard friendly.";
New-Alias -Name GEP -Value Get-ExecutionPolicy -Description "This purpose of this alias is to shorten the command of Get-ExecutionPolicy to something a little more keyboard friendly.";
function Restrict {SEP $Res; cls; GEP};
function Remote {SEP $RS; cls; GEP};
function Close {kill -Name cmd; kill -Name powershell_ise; kill -Name powershell};
#Stop-Process -Name cmd;
#Restrict;
#What about a secret Journal?;
#I would need to create a text file, change values, save the values, encrpyt the values. Next I would need to decrypt those values.;
#Can I create a script that makes Narnia, creates a script within narnia to delete itself on closing?;
$NULL=Read-Host "This is ends 1.ps1";